// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvVZk7zARG95wsnRjQq-WxkrwJVX3eW74',
    appId: '1:57965479792:web:c1f737d3795124db0f31b5',
    messagingSenderId: '57965479792',
    projectId: 'minichat-85cea',
    authDomain: 'minichat-85cea.firebaseapp.com',
    storageBucket: 'minichat-85cea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPnYAIID2VBhd3fMJAzm_y5Gm5KIO6lwU',
    appId: '1:57965479792:android:28fd87d823d19d130f31b5',
    messagingSenderId: '57965479792',
    projectId: 'minichat-85cea',
    storageBucket: 'minichat-85cea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4fFkxatgO7iVTkMkxdzPdo2ClSLiwrnA',
    appId: '1:57965479792:ios:8d30c7f21c9a90620f31b5',
    messagingSenderId: '57965479792',
    projectId: 'minichat-85cea',
    storageBucket: 'minichat-85cea.appspot.com',
    iosBundleId: 'com.example.chatMinits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4fFkxatgO7iVTkMkxdzPdo2ClSLiwrnA',
    appId: '1:57965479792:ios:dbabd5218a628a260f31b5',
    messagingSenderId: '57965479792',
    projectId: 'minichat-85cea',
    storageBucket: 'minichat-85cea.appspot.com',
    iosBundleId: 'com.example.chatMinits.RunnerTests',
  );
}
